### ISSUE TITLE
Markdown numbers overlap image previews

### ISSUE THREAD

**Issue by jstoessel** [C7C8/SoftEng-API-Site#14]
![image](https://user-images.githubusercontent.com/59942828/74969585-d63d0f80-53ea-11ea-988d-8d37d6562cc7.png)

When you open the Team G's API, the "1." is positioned over the picture which can make the words not visible.

**Team: S**

**Comment by C7C8** [comment]
Confirmed! What's your team name?

**Comment by C7C8** [comment]
Fixed in c1fa8c83405a8fe80735576e9bd39f4f50f7b02c and slated for release in v1.1.6
