### ISSUE TITLE
Validation limits on account creation

### ISSUE THREAD

**Issue by Synerin** [C7C8/SoftEng-API-Site#15]
**Describe the bug**
Not really a traditional bug (might even be a bit of a nitpick), but there seem to be very few limits for new usernames / passwords. 

From what I understand a username is organized like this:
- Non-empty String that contains nearly any character (not "@", ".", "<", ">", "(", ")", or " " )
- @ symbol
- Non-empty String that with more character limits, allowing zero or one "." as long as it's followed by any valid character(s)
- No longer than 75 characters

Passwords seem to have almost no limits, allowing for passwords composed of a single space " " character, or the length of an entire Wikipedia article. The only constraint would be that the length is at least one character.

**To Reproduce**
1. Go to https://apisite.crmyers.dev/login
2. Click on Email or Password
3. Try typing in an Email or Password that might not traditionally pass verification
4. See oddity

**Expected behavior**
An error message stating that the Username or Password does not fall within valid parameters.

**Screenshots**
![image](https://user-images.githubusercontent.com/36575784/75118705-662cc480-564a-11ea-8bc2-d392b8cb69b0.png)

**Team Letter**
T

**Comment by C7C8** [comment]
**On emails:** The requirement is that the email field must be a valid email address; there's a specific standards-compliant validation used (provided by Angular) to ensure that it could *in theory* be an email address, if a provider for it existed. In the future email verification will be a feature (i.e. the traditional "please verify your account before logging in" that you see on most services), but technically the username field works exactly as expected so I can't consider it a bug.

**On passwords:** There is no requirement on passwords, even a max length requirement! This is definitely an oversight of mine, I'll implement a max password length -- **bug confirmed**. As for minimum length or complexity requirements, I'll probably add a minimum length but not a complexity requirement. There's so much misinformation about the effectiveness of those, and a proper entropy-based requirement would be too technical for most people to understand, so I'll probably just post a list of password recommendations or something.

Thanks!

**Comment by C7C8** [comment]
Password max length (2048 characters) added in 1f95e6b2b27aa2ebf56c091fad800a24aee74ffc.
